DiseaseMapMVC/Models/ViewModels/Concrete/CountryViewModel.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DiseaseMapMVC.Models.ViewModels
{
    /// <summary>
    /// Модель представления для добавления страны
    /// </summary>
    public class CountryViewModel : IViewModel
    {
        /// <summary>
        /// Id страны
        /// </summary>
        [ScaffoldColumn(false)]
        public string? Id { get; set; }

        /// <summary>
        /// Название страны
        /// </summary>
        [Display(Name = "Name")]
        [Required(ErrorMessage = "NameRequired")]
        public string Name { get; set; }

    }
}

DiseaseMapMVC/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DiseaseMapMVC.Models.Converter;
using DiseaseMapMVC.Models.ViewModels;
using DiseaseMongoModel;
using Newtonsoft.Json;
using JqueryDataTables.ServerSide.AspNetCoreWeb.Models;
using DiseaseMapMVC.Resources.Models;

namespace DiseaseMapMVC.Controllers
{
    /// <summary>
    /// Контроллер грида стран
    /// </summary>
    public class CountryController : DataTableController
    {
        /// <summary>
        /// Репозиторий стран
        /// </summary>
        private MongoDbRepository<Country> _СountryRepository;

        /// <summary>
        /// Конвертер модели представления страны в сущность для работы с базой Mongo
        /// </summary>
        private CountryMongoToViewModelConverter<Country, CountryViewModel> _СountryConverter = new CountryMongoToViewModelConverter<Country, CountryViewModel>();

        /// <summary>
        /// Конструктор класса
        /// </summary>
        /// <param name="context">контекст Mongo</param>
        public CountryController(MongoContext context)
        {
            _СountryRepository = new MongoDbRepository<Country>(context);
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Метод загружает грид стран
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Load()
        {
            var data = GetSearchCountries();

            return GetJsonResult<Country>(data);
        }

        /// <summary>
        /// Метод обрабатывает нажатие кнопки Сохранить при создании или редактировании стран
        /// </summary>
        /// <param name="countryViewModel">модель страны, которую необходимо создать или отредактировать</param>
        /// <returns></returns>
        public IActionResult Save(CountryViewModel countryViewModel)
        {
            if (ModelState.IsValid)
            {
                var changeSuccess = false;

                if (!string.IsNullOrEmpty(countryViewModel.Id))
                {
                    var editCountry = _СountryRepository.GetById(countryViewModel.Id);

                    _СountryConverter.Convert(countryViewModel, editCountry);

                    changeSuccess = _СountryRepository.Update(editCountry);
                }
                else
                {
                    var country = _СountryConverter.Convert(countryViewModel);

                    changeSuccess = _СountryRepository.Create(country);
                }

                if (changeSuccess)
                {
                    return View("Index");
                }
                else
                {
                    return Content(ErrorMessages.SaveCountryError);
                }
            }
            else
                return PartialView("Editor", countryViewModel);
        }

        /// <summary>
        /// Метод открывает диалоговое окно для создания страны
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            return PartialView("Editor");
        }

        /// <summary>
        /// Метод редактирует выбранную запись страны
        /// </summary>
        /// <param name="id">id страны, которая будет редактироваться</param>
        /// <returns></returns>
        public IActionResult Edit(string id)
        {
            var editCountry = _СountryRepository.GetById(id);

            if (editCountry != null)
            {
                return PartialView("Editor", _СountryConverter.Convert(editCountry));
            }

            return Content(ErrorMessages.ErrorPage);
        }

        /// <summary>
        /// Метод удаляет выбранную запись страны
        /// </summary>
        /// <param name="id">id страны, которую необходимо удалить</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(string id)
        {
            var deletedCountry = _СountryRepository.GetById(id);

            if (deletedCountry != null)
            {
                _СountryRepository.Delete(deletedCountry);
            }

            var data = GetSearchCountries();

            return GetJsonResult<Country>(data);
        }
        
        /// <summary>
        /// Метод получает список записей, исходя из значения, введеного в строку поиска
        /// </summary>
        /// <returns>список записей</returns>
        private IEnumerable<Country> GetSearchCountries()
        {
            var searchValue = GetSearchValue();

            return _СountryRepository.SearchFor(e => e.Name.ToLower().Contains(searchValue));
        }
    }
}

DiseaseMapMVC/Views/Country/Editor.cshtml
@inject IViewLocalizer Localizer

@model CountryViewModel;

<link href="~/css/myStyles/errorMessage.css" rel="stylesheet" />

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("Save", "Country", FormMethod.Post, new { @class = "modal-content form-horizontal", role = "form" }))
{
    <div class="modal-header">
        <h4>@Localizer["CountryParameters"]</h4>
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <hr />

    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.Name)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success btn-default" value='@Localizer["Save"]'/>
        </div>
    </div>
}

DiseaseMapMVC/Views/Country/Index.cshtml
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = "Countries";
}

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.html5.min.js"></script>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<script>
    $(document).ready(function () {
        $("#countriesTable").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "dom": 'Bfrtip',
            "language": {
                "search": '@Localizer["Search"]',
                "infoEmpty": '@Localizer["InfoEmpty"]',
                "buttons": {
                    "pageLength": {
                        _: '@Localizer["10Rows"]'
                    }
                }
            },
            "ajax": {
                "url": "/Country/Load",
                "type": "POST",
                "datatype": "json"
            },
            "columnDefs": [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": false
                },
                {
                    "defaultContent": "-",
                    "targets": "_all"
                }
            ],
            "columns": [
                { "data": "id", "title": "Id", "autoWidth": true },
                { "data": "name", "title": '@Localizer["Name"]', "autoWidth": true },
                {
                    "render": function (data, type, full, meta) {
                        return '<a class="btn btn-info" href="/City/Index/' + full.id + '">@Localizer["Cities"]</a>';
                    }
                },
                {
                    "render": function (data, type, full, meta) {
                        return "<a href='#' class='btn btn-info' onclick=Edit('" + full.id + "');>@Localizer["Edit"]</a>";
                    }
                },
                {
                    data: null, render: function (data, type, row) {
                        return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.id + "');>@Localizer["Delete"]</a>";
                    }
                }
            ],
            "lengthMenu": [
                [ 10, 25, 50 ],
                [ '@Localizer["10Rows"]', '@Localizer["25Rows"]', '@Localizer["50Rows"]' ]
            ],
            "buttons": [
                {
                    text: '@Localizer["Add"]',
                    action: function (e, dt, node, config) {
                        Add();
                    }
                },
                'pageLength'
            ]
        });
    });

    function Edit(id) {
        var url = '@Url.Action("Edit", "Country", null)';

        $.post(url, { id: id }, function (data) {
            if (data) {
                $('#dialogContent').html(data);
                $('#modDialog').modal('show');
            } else {
                alert('@Localizer["ErrorMessage"]');
            }
        });
    }

    function DeleteData(id) {
        if (confirm('@Localizer["DeleteQuestion"]')) {
            Delete(id);
        } else {
            return false;
        }
    }


    function Delete(id) {
        var url = '@Url.Action("Delete", "Country", null)';

        $.post(url, { id: id }, function(data) {
            if (data) {
                var oTable = $('#countriesTable').DataTable();
                oTable.draw();
            } else {
                alert('@Localizer["ErrorMessage"]');
            }
        });
    }

    function Add(parameters) {
        var url = '@Url.Action("Add", "Country", null)';

        $.post(url, {  },
            function(data) {
                if (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                } else {
                    alert('@Localizer["ErrorMessage"]');
                }
            });
    }
</script>

<div class="container">
    <br />
    <div style="width: 90%; margin: 0 auto;">
        <table id="countriesTable" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>@Localizer["Name"]</th>
                    <th>@Localizer["Cities"]</th>
                    <th>@Localizer["Edit"]</th>
                    <th>@Localizer["Delete"]</th>
                </tr>
            </thead>
        </table>
    </div>
</div>