DiseaseMapMVC/Models/ViewModels/Concrete/CityViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace DiseaseMapMVC.Models.ViewModels
{
    /// <summary>
    /// Модель представления для добавления города
    /// </summary>
    public class CityViewModel : IViewModel
    {
        /// <summary>
        /// Id города
        /// </summary>
        [ScaffoldColumn(false)]
        public string? Id { get; set; }

        /// <summary>
        /// Id страны
        /// </summary>
        [ScaffoldColumn(false)]
        public string CountryId { get; set; }

        /// <summary>
        /// Название города
        /// </summary>
        [Display(Name = "Name")]
        [Required(ErrorMessage = "NameRequired")]
        public string Name { get; set; }

        /// <summary>
        /// Количество детей
        /// </summary>
        [Display(Name = "KidNumber")]
        [Range(0, int.MaxValue, ErrorMessage = "KidNumberRange")]
        public int KidNumber { get; set; }

        /// <summary>
        /// Количество подростков
        /// </summary>
        [Display(Name = "AdolescentNumber")]
        [Range(0, int.MaxValue, ErrorMessage = "AdolescentNumberRange")]
        public int AdolescentNumber { get; set; }

        /// <summary>
        /// Количество взрослых, работающих граждан
        /// </summary>
        [Display(Name = "AdultNumber")]
        [Range(0, int.MaxValue, ErrorMessage = "AdultNumberRange")]
        public int AdultNumber { get; set; }

        /// <summary>
        /// Количество пенсионеров
        /// </summary>
        [Display(Name = "RetireeNumber")]
        [Range(0, int.MaxValue, ErrorMessage = "RetireeNumberRange")]
        public int RetireeNumber { get; set; }
    }
}

DiseaseMapMVC/Controllers/CityController.cs
using DiseaseMapMVC.Models.Converter;
using DiseaseMapMVC.Models.ViewModels;
using DiseaseMapMVC.Resources.Models;
using DiseaseMongoModel;
using JqueryDataTables.ServerSide.AspNetCoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DiseaseMapMVC.Controllers
{
    /// <summary>
    /// Контроллер грида городов
    /// </summary>
    public class CityController : DataTableController
    {
        /// <summary>
        /// Репозиторий городов
        /// </summary>
        private MongoDbRepository<City> _CityRepository;

        /// <summary>
        /// Конвертер модели представления города в сущность для работы с базой Mongo
        /// </summary>
        private CityMongoToViewModelConverter<City, CityViewModel> _CityConverter = new CityMongoToViewModelConverter<City, CityViewModel>();

        /// <summary>
        /// Конструктор класса
        /// </summary>
        /// <param name="context">контекст Mongo</param>
        public CityController(MongoContext context)
        {
            _CityRepository = new MongoDbRepository<City>(context);
        }

        public IActionResult Index(string id)
        {
            return View(new Country { Id = id });
        }

        /// <summary>
        /// Метод загружает грид городов
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Load(string countryId)
        {
            var data = GetCities(countryId);

            return GetJsonResult<CityViewModel>(data);
        }

        /// <summary>
        /// Метод открывает диалоговое окно для создания города
        /// </summary>
        /// <param name="countryId">id страны, для которой будет создаваться город</param>
        /// <returns></returns>
        public IActionResult Add(string countryId)
        {
            if (!string.IsNullOrEmpty(countryId))
            {
                return PartialView("Editor", new CityViewModel
                {
                    CountryId = countryId
                });
            }

            return Content(ErrorMessages.ErrorPage);
        }

        /// <summary>
        /// Метод редактирует выбранную запись города
        /// </summary>
        /// <param name="id">id города, который будет редактироваться</param>
        /// <returns></returns>
        public IActionResult Edit(string id)
        {
            var editCity = _CityRepository.GetById(id);

            if (editCity != null)
            {
                return PartialView("Editor", _CityConverter.Convert(editCity));
            }

            return Content(ErrorMessages.ErrorPage);
        }

        /// <summary>
        /// Метод обрабатывает нажатие кнопки Сохранить при создании или редактировании города
        /// </summary>
        /// <param name="cityViewModel">модель города, который необходимо создать или отредактировать</param>
        /// <returns></returns>
        public IActionResult Save(CityViewModel cityViewModel)
        {
            if (ModelState.IsValid)
            {
                var changeSuccess = false;

                if (!string.IsNullOrEmpty(cityViewModel.Id))
                {
                    var editCity = _CityRepository.GetById(cityViewModel.Id);

                    _CityConverter.Convert(cityViewModel, editCity);

                    changeSuccess = _CityRepository.Update(editCity);
                }
                else
                {
                    var city = _CityConverter.Convert(cityViewModel);

                    changeSuccess = _CityRepository.Create(city);
                }

                if (changeSuccess)
                {
                    return View("Index", new Country { Id = cityViewModel.CountryId });
                }
                else
                {
                    return Content(ErrorMessages.SaveCityError);
                }
            }
            else
                return PartialView("Editor", cityViewModel);
        }

        /// <summary>
        /// Метод удаляет выбранную запись города
        /// </summary>
        /// <param name="id">id города, который необходимо удалить</param>
        /// <param name="countryId">id страны, в которой находится удаляемый город</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(string id, string countryId)
        {
            var deletedCity = _CityRepository.GetById(id);

            if (deletedCity != null)
            {
                _CityRepository.Delete(deletedCity);
            }

            var data = GetCities(countryId);

            return GetJsonResult<CityViewModel>(data);
        }

        /// <summary>
        ///  Метод получает список записей, исходя из значения, введеного в строку поиска
        /// </summary>
        /// <param name="countryId">id станы, в которой находятся города</param>
        /// <returns></returns>
        private IEnumerable<CityViewModel> GetCities(string countryId)
        {
            var searchValue = GetSearchValue();

            var cities = _CityRepository.SearchFor(e => e.CountryId == new ObjectId(countryId) && e.Name.ToLower().Contains(searchValue));

            return cities.Select(c => _CityConverter.Convert(c));
        }
    }
}

DiseaseMapMVC/Views/City/Editor.cshtml
@inject IViewLocalizer Localizer

@model CityViewModel;

<link href="~/css/myStyles/errorMessage.css" rel="stylesheet" />

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

@using (Html.BeginForm("Save", "City", FormMethod.Post, new { id = "editForm", @class = "modal-content form-horizontal", role = "form" }))
{
    <div class="modal-header">
        <h4>@Localizer["CityParameters"]</h4>
        <button id="closeButton" class="close" data-dismiss="modal" area-hidden="true">X</button>
    </div>
    <hr />

    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CountryId)

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.Name)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.KidNumber, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.KidNumber)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.KidNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AdolescentNumber, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.AdolescentNumber)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.AdolescentNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AdultNumber, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.AdultNumber)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.AdultNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RetireeNumber, new { @class = "col-md-6 control-label" })
        @Html.ValidationMessageFor(m => m.RetireeNumber)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RetireeNumber, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-success btn-default" value="@Localizer["Save"]" />
        </div>
    </div>
}

DiseaseMapMVC/Views/City/Index.cshtml
@inject IViewLocalizer Localizer

@model Country;

@{
    ViewBag.Title = "Cities";
}

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<link href="https://cdn.datatables.net/buttons/1.6.5/css/buttons.dataTables.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.html5.min.js"></script>

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>

<script>
    $(document).ready(function() {
        $("#citiesTable").DataTable({
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paging": true,
            "info": true,
            "dom": 'Bfrtip',
            "language": {
                "search": '@Localizer["Search"]',
                "infoEmpty": '@Localizer["InfoEmpty"]',
                "buttons": {
                    "pageLength": {
                        _: '@Localizer["10Rows"]'
                    }
                }
            },
            "ajax": {
                "url": '@Url.Action("Load", "City", new {countryId = Model.Id})',
                "type": "POST",
                "datatype": "json"
            },
            "columnDefs": [
                {
                    "targets": [0],
                    "visible": false,
                    "searchable": false
                },
                {
                    "targets": [1],
                    "visible": false,
                    "searchable": false
                },
                {
                    "defaultContent": "-",
                    "targets": "_all"
                }
            ],
            "columns": [
                { "data": "id", "title": "Id", "autoWidth": true },
                { "data": "countryId", "title": "countryId", "autoWidth": true },
                { "data": "name", "title": '@Localizer["Name"]', "autoWidth": false },
                { "data": "kidNumber", "title": '@Localizer["KidNumber"]', "autoWidth": false },
                { "data": "adolescentNumber", "title": '@Localizer["AdolescentNumber"]', "autoWidth": false },
                { "data": "adultNumber", "title": '@Localizer["AdultNumber"]', "autoWidth": false },
                { "data": "retireeNumber", "title": '@Localizer["RetireeNumber"]', "autoWidth": false },
                {
                    "render": function (data, type, full, meta) {
                        return "<a href='#' class='btn btn-info' onclick=Edit('" + full.id + "');>@Localizer["Edit"]</a>";
                    }
                },
                {
                    data: null, render: function (data, type, row) {
                        return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.id + "');>@Localizer["Delete"]</a>";
                    }
                }
            ],
            "lengthMenu": [
                [10, 25, 50],
                ['@Localizer["10Rows"]', '@Localizer["25Rows"]', '@Localizer["50Rows"]' ]
            ],
            "buttons": [
                {
                    text: '@Localizer["Add"]',
                    action: function (e, dt, node, config) {
                        Add();
                    }
                },
                'pageLength'
            ]
        });
    });

    function Edit(id) {
        var url = '@Url.Action("Edit", "City", null)';

        $.post(url, { id: id }, function (data) {
            if (data) {
                $('#dialogContent').html(data);
                $('#modDialog').modal('show');
            } else {
                alert('@Localizer["ErrorMessage"]');
            }
        });
    }

    function DeleteData(id) {
        if (confirm('@Localizer["DeleteQuestion"]')) {
            Delete(id);
        } else {
            return false;
        }
    }


    function Delete(id) {
        var url = '@Url.Action("Delete", "City", new { countryId = Model.Id })';

        $.post(url, { id: id }, function(data) {
            if (data) {
                var oTable = $('#citiesTable').DataTable();
                oTable.draw();
            } else {
                alert('@Localizer["ErrorMessage"]');
            }
        });
    }

    function Add(parameters) {
        var url = '@Url.Action("Add", "City", new { countryId = Model.Id })';

        $.post(url, {  },
            function(data) {
                if (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                } else {
                    alert('@Localizer["ErrorMessage"]');
                }
            });
    }

</script>

<div class="container">
    <br />
    <div style="width: 90%; margin: 0 auto;">
        <table id="citiesTable" class="table table-striped table-bordered dt-responsive nowrap" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>CountryId</th>
                    <th>@Localizer["Name"]</th>
                    <th>@Localizer["KidNumber"]</th>
                    <th>@Localizer["AdolescentNumber"]</th>
                    <th>@Localizer["AdultNumber"]</th>
                    <th>@Localizer["RetireeNumber"]</th>
                    <th>@Localizer["Edit"]</th>
                    <th>@Localizer["Delete"]</th>
                </tr>
            </thead>
        </table>
    </div>
</div>